#!/usr/bin/env bash

if [ "`id -u`" -eq 0 ]; then
  prefix=`kde-config --install data --expandvars`
  install_dir="${prefix}/kate/pyplugins/directory_project"
  echo "Installing system wide: $install_dir"
  mkdir -p $install_dir
else
  prefix=`kde-config --localprefix --expandvars`
  install_dir="${prefix}share/apps/kate/pyplugins/directory_project"
  echo "Installing locally: $install_dir"
  mkdir -p $install_dir
  cp directory_project.py $install_dir
fi